//! Multicall entry point: `argv[0]` names the utility, the rest are its
//! arguments. Exits with the utility's status. Generated by gen.py.
//!
//! The host passes the shell's working directory as `PWD`; wasi-libc starts
//! every process at `/`, so it is applied before dispatch. Unknown names exit
//! 127 like a shell's "command not found".

use std::ffi::OsString;

fn main() {
    if let Some(pwd) = std::env::var_os("PWD") {
        let _ = std::env::set_current_dir(pwd);
    }
    let args: Vec<OsString> = std::env::args_os().collect();
    let name = args
        .first()
        .and_then(|a| a.to_str())
        .unwrap_or_default()
        .to_string();
    if !UTILS.contains(&name.as_str()) {
        eprintln!("coreutils: {name}: unknown utility");
        std::process::exit(127);
    }
    if let Err(e) = uucore::locale::setup_localization(&name) {
        eprintln!("{name}: could not init localization: {e}");
        std::process::exit(99);
    }
    std::process::exit(dispatch(&name, args.into_iter()));
}

/// Utilities this guest provides, sorted.
const UTILS: &[&str] = &["b2sum", "base32", "base64", "basename", "basenc", "cat", "cksum", "comm", "cp", "csplit", "cut", "date", "dd", "dir", "dircolors", "dirname", "echo", "expand", "expr", "factor", "false", "fmt", "fold", "head", "join", "link", "ln", "ls", "md5sum", "mkdir", "mktemp", "mv", "nl", "nproc", "numfmt", "od", "paste", "pathchk", "pr", "printenv", "printf", "ptx", "pwd", "readlink", "realpath", "rm", "rmdir", "seq", "sha1sum", "sha224sum", "sha256sum", "sha384sum", "sha512sum", "shred", "shuf", "sort", "split", "sum", "tail", "tee", "test", "touch", "tr", "true", "truncate", "tsort", "unexpand", "uniq", "unlink", "vdir", "wc"];

fn dispatch(name: &str, args: impl uucore::Args) -> i32 {
    match name {
        "b2sum" => uu_b2sum::uumain(args),
        "base32" => uu_base32::uumain(args),
        "base64" => uu_base64::uumain(args),
        "basename" => uu_basename::uumain(args),
        "basenc" => uu_basenc::uumain(args),
        "cat" => uu_cat::uumain(args),
        "cksum" => uu_cksum::uumain(args),
        "comm" => uu_comm::uumain(args),
        "cp" => uu_cp::uumain(args),
        "csplit" => uu_csplit::uumain(args),
        "cut" => uu_cut::uumain(args),
        "date" => uu_date::uumain(args),
        "dd" => uu_dd::uumain(args),
        "dir" => uu_dir::uumain(args),
        "dircolors" => uu_dircolors::uumain(args),
        "dirname" => uu_dirname::uumain(args),
        "echo" => uu_echo::uumain(args),
        "expand" => uu_expand::uumain(args),
        "expr" => uu_expr::uumain(args),
        "factor" => uu_factor::uumain(args),
        "false" => uu_false::uumain(args),
        "fmt" => uu_fmt::uumain(args),
        "fold" => uu_fold::uumain(args),
        "head" => uu_head::uumain(args),
        "join" => uu_join::uumain(args),
        "link" => uu_link::uumain(args),
        "ln" => uu_ln::uumain(args),
        "ls" => uu_ls::uumain(args),
        "md5sum" => uu_md5sum::uumain(args),
        "mkdir" => uu_mkdir::uumain(args),
        "mktemp" => uu_mktemp::uumain(args),
        "mv" => uu_mv::uumain(args),
        "nl" => uu_nl::uumain(args),
        "nproc" => uu_nproc::uumain(args),
        "numfmt" => uu_numfmt::uumain(args),
        "od" => uu_od::uumain(args),
        "paste" => uu_paste::uumain(args),
        "pathchk" => uu_pathchk::uumain(args),
        "pr" => uu_pr::uumain(args),
        "printenv" => uu_printenv::uumain(args),
        "printf" => uu_printf::uumain(args),
        "ptx" => uu_ptx::uumain(args),
        "pwd" => uu_pwd::uumain(args),
        "readlink" => uu_readlink::uumain(args),
        "realpath" => uu_realpath::uumain(args),
        "rm" => uu_rm::uumain(args),
        "rmdir" => uu_rmdir::uumain(args),
        "seq" => uu_seq::uumain(args),
        "sha1sum" => uu_sha1sum::uumain(args),
        "sha224sum" => uu_sha224sum::uumain(args),
        "sha256sum" => uu_sha256sum::uumain(args),
        "sha384sum" => uu_sha384sum::uumain(args),
        "sha512sum" => uu_sha512sum::uumain(args),
        "shred" => uu_shred::uumain(args),
        "shuf" => uu_shuf::uumain(args),
        "sort" => uu_sort::uumain(args),
        "split" => uu_split::uumain(args),
        "sum" => uu_sum::uumain(args),
        "tail" => uu_tail::uumain(args),
        "tee" => uu_tee::uumain(args),
        "test" => uu_test::uumain(args),
        "touch" => uu_touch::uumain(args),
        "tr" => uu_tr::uumain(args),
        "true" => uu_true::uumain(args),
        "truncate" => uu_truncate::uumain(args),
        "tsort" => uu_tsort::uumain(args),
        "unexpand" => uu_unexpand::uumain(args),
        "uniq" => uu_uniq::uumain(args),
        "unlink" => uu_unlink::uumain(args),
        "vdir" => uu_vdir::uumain(args),
        "wc" => uu_wc::uumain(args),
        _ => 127,
    }
}
