#!/usr/bin/env python3
"""Regenerate Cargo.toml and src/main.rs from utils.txt (one utility per line).

Run by build.sh; commit the outputs. Utilities must build for wasm32-wasip1
(uutils' `feat_wasm` set). Left out on purpose: utilities that
only report on or wait for the host (uname, arch, tty, hostid, nice, sleep,
yes), which bashkit answers itself, and ones that build but cannot work on
wasip1 (dd spawns a thread on every copy, tac needs a temp dir for stdin).
"""

from pathlib import Path

UUTILS = "0.12.0"
here = Path(__file__).resolve().parent
utils = sorted({u.strip() for u in (here / "utils.txt").read_text().splitlines() if u.strip()})
(here / "utils.txt").write_text("\n".join(utils) + "\n")

deps = "\n".join(f'uu_{u} = "={UUTILS}"' for u in utils)
(here / "Cargo.toml").write_text(f'''# Multicall uutils/coreutils guest for bashkit's `wasm-coreutils` feature.
# Generated by gen.py from utils.txt; built for wasm32-wasip1 by build.sh.
# Not part of the bashkit workspace.
#
# Decisions (see knowledge/runtimes/wasm-coreutils.md):
# - Own main instead of uutils' `coreutils` binary: it applies `PWD` as the
#   working directory first (wasi-libc starts at `/`), and the utility list is
#   ours.
# - Pinned to one uutils release; every uu_* crate is the same version.

[package]
name = "bashkit-coreutils-guest"
version = "0.0.0"
edition = "2024"
publish = false
license = "MIT"

[workspace]

[dependencies]
uucore = {{ version = "={UUTILS}" }}
{deps}

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
''')

names = ", ".join(f'"{u}"' for u in utils)
arms = "\n".join(f'        "{u}" => uu_{u}::uumain(args),' for u in utils)
(here / "src/main.rs").write_text(f'''//! Multicall entry point: `argv[0]` names the utility, the rest are its
//! arguments. Exits with the utility's status. Generated by gen.py.
//!
//! The host passes the shell's working directory as `PWD`; wasi-libc starts
//! every process at `/`, so it is applied before dispatch. Unknown names exit
//! 127 like a shell's "command not found".
//!
//! A panic prints one fixed line instead of Rust's default report (source
//! paths, toolchain hash, `Debug` payloads); the host then reports the abort.

use std::ffi::OsString;

fn main() {{
    std::panic::set_hook(Box::new(|_| {{
        let name = std::env::args().next().unwrap_or_default();
        eprintln!("{{name}}: internal error");
    }}));
    if let Some(pwd) = std::env::var_os("PWD") {{
        let _ = std::env::set_current_dir(pwd);
    }}
    let args: Vec<OsString> = std::env::args_os().collect();
    let name = args
        .first()
        .and_then(|a| a.to_str())
        .unwrap_or_default()
        .to_string();
    if !UTILS.contains(&name.as_str()) {{
        eprintln!("coreutils: {{name}}: unknown utility");
        std::process::exit(127);
    }}
    if let Err(e) = uucore::locale::setup_localization(&name) {{
        eprintln!("{{name}}: could not init localization: {{e}}");
        std::process::exit(99);
    }}
    std::process::exit(dispatch(&name, args.into_iter()));
}}

/// Utilities this guest provides, sorted.
const UTILS: &[&str] = &[{names}];

fn dispatch(name: &str, args: impl uucore::Args) -> i32 {{
    match name {{
{arms}
        _ => 127,
    }}
}}
''')
