true; echo "true=$?"
false; echo "false=$?"
! false; echo "neg=$?"
false | true; echo "pipe=$? ps=${PIPESTATUS[*]}"
true | false | true; echo "ps=${PIPESTATUS[@]} n=${#PIPESTATUS[@]}"
(exit 300); echo "300->$?"
(exit -1); echo "-1->$?"
naoexiste 2>/dev/null; echo "cnf=$?"
./sem_permissao 2>/dev/null; echo "noexec=$?"
